language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
install: yarn
jobs:
  include:
    - stage: lint
      script: yarn run test:lint
    - stage: coverage
      script: bash ./scripts/.travis-coverage.sh
    - # Node 11 test
      script: bash ./scripts/.travis-coverage.sh
      node_js:
        - "11"
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
