parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: Lint
  condition: succeeded()
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node 10:
        nodeVersion: '10.x'
      Node 11:
        nodeVersion: '11.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    - bash: scripts/.azure-coverage.sh
      env:
        NODE_VERSION: $(nodeVersion)
        PLATFORM: $({ parameters.name })
