parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: Lint
  condition: succeeded()
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node 10:
        nodeVersion: '10.x'
      Node 11:
        nodeVersion: '11.x'
      Node 12:
        nodeVersion: '12.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    - script: 'yarn'
      displayName: 'Install Dependencies'
    - script: 'yarn run test:coverage'
      displayName: 'Run Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(System.DefaultWorkingDirectory)/test-results.xml
      displayName: 'Publish Test Results'
    - script: 'yarn run coverage:azure'
      displayName: 'Generate Reports'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      displayName: 'Publish Coverage Results'
