parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: Lint
  condition: succeeded()
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node 10:
        nodeVersion: '10.x'
      Node 11:
        nodeVersion: '11.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    - script: yarn
    - bash: |
        set -e

        # For Node != 10.x or Platform != Linux, do nothing
        if [ "$NODE_VERSION" != "10.x" -o "$PLATFORM" != "Linux" ]; then
          echo -e "Build triggered on ${PLATFORM} - Node v${NODE_VERSION} - testing without reporting."
          yarn run test:coverage
          exit 0
        fi

        echo -e "Build triggered on ${PLATFORM} - Node v${NODE_VERSION} - testing and reporting coverage."

        yarn run test:coverage

        yarn run coveralls
      env:
        PLATFORM: ${{ parameters.name }}
        NODE_VERSION: $(nodeVersion)
        COVERALLS_SERVICE_NAME: 'Azure Pipelines'
        COVERALLS_REPO_TOKEN: $(coverallsRepoToken)
