name: ESLint

on:
  push:
    branches:
      - master
      - stable
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Deps
      run: yarn
    - name: Run ESLint
      uses: bdistin/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
