name: ESLint

on:
  push:
    branches:
      - master
      - stable
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ESLint
      uses: gimenete/eslint-action@1.0
